CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name text not null,
    note_content text not null,
    modified timestamp DEFAULT now(),
    folder_id INTEGER references folders(id) not null

);